# Metadata store config
metastore_type: postgres
metastore_config:
  pg_string: user=postgres password=password dbname=dataman sslmode=disable

# actual store configuration
storage_type: memstorage
storage_config: {}

# config for the HTTP api
http_api:
  addr: ":8081"
